### ISSUE TITLE
Fix padding on update page

### ISSUE THREAD

**Issue by Stormgren** [Stormgren/Contacts-Manager-App-FrontEnd-Part#10]
Padding on top and bottom needs to be increased more so the page would become more visually appealing

**Comment by amrs-tech** [comment]
How to contribute to this issue ?
Where can i find preview ?

**Comment by Stormgren** [comment]
Thank you, but there is no need for that, I'm just writing notes for myself so I would know what to fix as I am learning to build projects.

**Comment by amrs-tech** [comment]
@Stormgren Okay :)
